# Generated by Django 2.1.1 on 2019-03-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_post', models.CharField(default='', max_length=10000000000)),
                ('pub_date', models.DateTimeField()),
                ('author', models.CharField(max_length=200)),
            ],
        ),
    ]
