# Generated by Django 2.1.1 on 2019-03-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190324_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
