# Generated by Django 2.1.1 on 2019-03-25 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20190325_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_save', models.CharField(default='', max_length=1000000000)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('post_author', models.CharField(default='', max_length=200)),
                ('delete_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
