# Generated by Django 2.1.1 on 2019-04-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_postadd_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadd',
            name='post_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
