# Generated by Django 2.1.1 on 2019-05-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20190504_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd',
            name='post_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
