# Generated by Django 2.1.1 on 2019-05-05 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_usersignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='delete_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
